//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suzianna.Reporting.Tests.Unit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFeaturesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFeaturesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suzianna.Reporting.Tests.Unit.Resources.TestFeaturesResources", typeof(TestFeaturesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to renew my membership more easily As a Frequent Flyer member I want to be able to renew my membership online..
        /// </summary>
        internal static string OnlineMembershipRenewal_Description {
            get {
                return ResourceManager.GetString("OnlineMembershipRenewal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online membership renewal.
        /// </summary>
        internal static string OnlineMembershipRenewal_Title {
            get {
                return ResourceManager.GetString("OnlineMembershipRenewal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a store owner In order to keep track of stock I want to add items back to stock when they&apos;re returned..
        /// </summary>
        internal static string ReturnsGoToStock_Description {
            get {
                return ResourceManager.GetString("ReturnsGoToStock_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns go to stock.
        /// </summary>
        internal static string ReturnsGoToStock_Title {
            get {
                return ResourceManager.GetString("ReturnsGoToStock_Title", resourceCulture);
            }
        }
    }
}
